#!/bin/bash

# z3bra - (c) wtfpl 2014
# Manage a todo list.
# The file is just plain text, with one line per task.
# This script just provide "shorter" commands to append to the file and display
# its content. For more complex tasks, use other tools like `sed`.

# Where is the file?
TODO=${TODO:-$HOME/.todo}

list() {
    test -f $TODO && nl $TODO
}

append() {
    echo "$*" >> $TODO
}

delete() {
    test -n "$1" || exit 1
    sed -i "${1}d" $TODO
}

test "$1" = '-d' && delete "$2" && exit 0

test -n "$*" && append $* || list

exit 0
